fix publish CI and add public api job

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,24 +26,46 @@ env:
   RUST_BACKTRACE: short
 
 jobs:
+  deny-public-api-changes:
+    runs-on: ubuntu-latest
+    steps:
+      # Full git history needed
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      # Install nightly (stable is already installed)
+      - uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: nightly
+          override: true
+
+      # Install and run cargo public-api and deny any API diff
+      - run: cargo install cargo-public-api@0.14.0
+      - run: |
+          diff -u public-api.txt <(cargo +nightly-2022-08-15 public-api) ||
+              (echo '\nFAIL: Public API changed! To bless, `git commit` the result of `cargo +nightly-2022-08-15 public-api > public-api.txt`' && exit 1)
   publish:
     name: Publish to crates.io
     continue-on-error: false
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        package:
+          - fastcrypto
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-        with:
-          persist-credentials: false
       - name: Check semver
         uses: obi1kenobi/cargo-semver-checks-action@v1
         with:
-          crate-name: fastcrypto
-          version-tag-prefix: fastcrypto-v
+          crate-name: ${{ matrix.package }}
+          version-tag-prefix: ${{ matrix.package }}-v
       - id: check
         run: |
           set +e
-          ./scripts/is_version_already_uploaded.sh fastcrypto
+          ./scripts/is_version_already_uploaded.sh ${{ matrix.package }}
           export EXIT_CODE="$?"
           set -e
           if [[ "$EXIT_CODE" == "7" ]]; then
@@ -58,13 +80,13 @@ jobs:
         if: steps.check.outputs.is_new_version == 'yes'
         run: |
           set -euxo pipefail
-          export CURRENT_VERSION="$(./scripts/get_current_version.sh fastcrypto)"
-          git tag "fastcrypto-v$CURRENT_VERSION"
-          git push origin "fastcrypto-v$CURRENT_VERSION"
+          export CURRENT_VERSION="$(./scripts/get_current_version.sh ${{ matrix.package }})"
+          git tag "${{ matrix.package }}-v$CURRENT_VERSION"
+          git push origin "${{ matrix.package }}-v$CURRENT_VERSION"
       - uses: actions-rs/toolchain@v1
         if: steps.check.outputs.is_new_version == 'yes'
-      - name: Publish
+      - name: Publish fastcrypto
         if: steps.check.outputs.is_new_version == 'yes'
         env:
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-        run: cargo publish --dry-run
+        run: cargo publish
